import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primaryYellow: "var(--primary-yellow)",
        primaryBlue: "var(--primary-blue)",
        blueText: "var(--blue-text)",
        surfaceCream: "var(--surface-cream)",
        accentYellow: "var(--accent-yellow)",
        accentYellowHover: "var(--accent-yellow-hover)",
        navBg: "var(--nav-bg)",
        pageHeaderBg: "var(--page-header-bg)",
        pageHeaderText: "var(--page-header-text)",
        formBg: "var(--form-bg)",
        formText: "var(--form-text)",
        inputBg: "var(--input-bg)",
        inputBorder: "var(--input-border)",
        inputText: "var(--input-text)",
        hoverBorder: "var(--hover-border)",
        cardBg: "var(--card-bg)",
        cardTitle: "var(--card-title)",
        cardText: "var(--card-text)",
        heroPanelBg: "var(--hero-panel-bg)",
        captionBg: "var(--caption-bg)",
        navCurrent: "var(--nav-current)",
        navShadow: "var(--nav-shadow-color)",
        navShadowHover: "var(--nav-shadow-color-hover)",
        footerBg: "var(--footer-bg)",
      },
    },
  },
  plugins: [],
  safelist: [
    "hover:bg-slate-50",
    "hover:bg-slate-100",
    "hover:bg-slate-200",
    "hover:bg-slate-300",
    "hover:bg-slate-400",
    "hover:bg-slate-500",
    "hover:bg-slate-600",
    "hover:bg-slate-700",
    "hover:bg-slate-800",
    "hover:bg-slate-900",
    "hover:text-white",
    "hover:text-black",
  ],
} satisfies Config;
